### ISSUE TITLE
Unknown Config Object "lis2dw"

### ISSUE THREAD

**Issue by okeightysix** [MRX8024/motors-sync#10]
![image](https://github.com/user-attachments/assets/19f3fb9b-cdee-4d45-a59e-a8bc99fcab70)

Hi after updating to V1.1.0-45-g2ec826dd i start to get this error. 

Any ideas?

**Comment by MRX8024** [comment]
Hello, please provide klippy.log

**Comment by gogsi1** [comment]
> Hello, please provide klippy.log
![Снимок экрана 2024-09-29 134929](https://github.com/user-attachments/assets/76311efb-3f50-46d4-9533-f5
[klippy.log](https://github.com/user-attachments/files/17178623/klippy.log)
3a7e5b4d21)

**Comment by MRX8024** [comment]
Detect your accelerometer before [motors_sync], i.e.:

`[cartographer]`
`...`

`[adxl345]`
`cs_pin = cartographer:PA3`
`spi_bus = spi1`

`[motors_sync]`
`...`

**Comment by okeightysix** [comment]
> Detect your accelerometer before `[motors_sync]`, i.e.:
> 
> `[cartographer]` `...`
> 
> `[adxl345]` `cs_pin = cartographer:PA3` `spi_bus = spi1`
> 
> `[motors_sync]` `...`

it worked thank you and sorry for late answer i couldn't be able to provide log since i was away. But after changing the order it worked :)
