### ISSUE TITLE
SYNC_MOTORS_CALIBRATE not generating graphs or data

### ISSUE THREAD

**Issue by recrudesce** [MRX8024/motors-sync#12]
Exactly the same issue as here: https://github.com/MRX8024/motors-sync/issues/11

Latest code, it's doing the relevant 10 iterations, but then never generates any output or gives any results.  No processes exist either that would indicate it's doing anything.

I am running DangerKlipper bleeding-edge-v2 branch on a Raspberry Pi running mainsailOS.

**Comment by MRX8024** [comment]
Hi, first attach klipper.log, for example via [link](https://coderus.openrepos.net/klipper_logs)

**Comment by MRX8024** [comment]
Switch branch: `cd ~/motors-sync && git checkout test && git pull --force`, repeat the sync_cal and show what will happen
