### ISSUE TITLE
Could you include limited_corexy  as one of the valids Kinematics?

### ISSUE THREAD

**Issue by erlis** [MRX8024/motors-sync#17]
I'm using Danger Klipper and they have a Kinematics named limited_corexy that when used I can specify a different acceleration for X and Y, upon other features. 

motors_sync will not recognize this as a valid kinematic and will throw an error. Is it possible to include it as a valid corexy kinematic? 

You can check it here: 
https://dangerklipper.io/Config_Reference.html?h=limited_corexy#corexy-kinematics-with-limits-for-x-and-y-axes

Thanks

**Comment by MRX8024** [comment]
Hi, it's already included in the dev branch, I'm currently rewriting the documentation and it will be added to main soon.

**Comment by erlis** [comment]
Oh awesome, then I'm closing this! 

Thanks a lot
