### ISSUE TITLE
SYNC_MOTORS with tuned ROTATION_DISTANCE

### ISSUE THREAD

**Issue by FlorentBroise** [MRX8024/motors-sync#7]
![image](https://github.com/MRX8024/motors-sync/assets/93141411/b0183daa-6d7d-4c65-8d0d-eccce60bc914)
Hi
As I'm using custom rotation_distance values for XY Z to make perfect dimensionned parts (Not the only one I presume), is there a solution for your mod to work with another value than a round one (40) put with 39.xxx by exemple?

Thanks in advance

**Comment by MRX8024** [comment]
Hello, I still dont receive notifications :) I believe that it is incorrect to edit the size of the prints by editing the distance of the pulleys; they are always machined to certain constants. This should be done with a slicer or third-party programs. However, I will add rounding to the nearest integer.

-Maxim

**Comment by FlorentBroise** [comment]
Are you aware of another solution to match the dimentionnal accuracy depending of material expension, Nozzle width, and some other factor that can impact accuracies? Scaling is another option but give some other dimentionnal issue...

**Comment by MRX8024** [comment]
My prints suit my requirements with normal scaling inside the slicer. If your model geometry (length, width, etc.) changes depending on the width of the nozzle, then when changing the nozzle you will have to use a different `rotation_distance`... However, despite the fact that this does not apply to the current repository, you can describe the problem in more detail , and if I know the answer, I will help you.
